version: '3'
services:
  taas_api:
    image: tc_tagger_api:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DYNAMODB_URL=http://host.docker.internal:8000
      - IS_LOCAL_DB=true
